# Generated by Django 5.2.6 on 2025-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id в Телеграм'),
        ),
    ]
