# Generated by Django 5.2.6 on 2025-09-27 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место')),
                ('periodicity', models.PositiveIntegerField(default=7, verbose_name='периодичность в неделю')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='время')),
                (
                    'execution_time',
                    models.PositiveIntegerField(default=120, verbose_name='время выполнения (секунды)'),
                ),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение')),
                ('is_published', models.BooleanField(default=False, verbose_name='публичность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                (
                    'related_habit',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='i_can.habit',
                        verbose_name='связанная привычка',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='habits',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'db_table': 'habits',
                'ordering': ['user', '-created_at'],
            },
        ),
    ]
