# Generated by Django 5.2.6 on 2025-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_can', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_reminder_send',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Напоминание отправлено'),
        ),
    ]
