# Generated by Django 5.2.6 on 2025-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_can', '0002_habit_is_reminder_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.PositiveIntegerField(
                blank=True, default=120, null=True, verbose_name='время выполнения (секунды)'
            ),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='периодичность в неделю'),
        ),
    ]
