# Generated by Django 5.2.6 on 2025-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_can', '0003_alter_habit_execution_time_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='периодичность в неделю'),
        ),
    ]
