# Generated by Django 5.2.6 on 2025-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_can', '0004_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='update_reminder_send_flag',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки напоминания'),
        ),
    ]
